import {
  SiReact,
  SiNodedotjs,
  SiTypescript,
  SiJavascript,
  SiFastapi,
  SiNestjs,
  SiRust,
  SiGo,
  SiPostgresql,
  SiMongodb,
  SiDocker,
  SiGit,
} from "react-icons/si";
import type { TechIcon, HeroTaglinePart } from "../types/hero.types";

export const TECH_ICONS: TechIcon[] = [
  {
    Icon: SiReact,
    color: "#61DAFB",
    x: -38,
    y: -22,
    size: 52,
    delay: 0.05,
    duration: 1.25,
  },
  {
    Icon: SiTypescript,
    color: "#3178C6",
    x: -10,
    y: -30,
    size: 44,
    delay: 0.18,
    duration: 1.05,
  },
  {
    Icon: SiJavascript,
    color: "#F7DF1E",
    x: 16,
    y: -28,
    size: 40,
    delay: 0.0,
    duration: 1.35,
  },
  {
    Icon: SiFastapi,
    color: "#05998B",
    x: 34,
    y: -18,
    size: 46,
    delay: 0.24,
    duration: 1.1,
  },
  {
    Icon: SiNodedotjs,
    color: "#539E43",
    x: -30,
    y: 8,
    size: 50,
    delay: 0.12,
    duration: 1.2,
  },
  {
    Icon: SiGit,
    color: "#F05033",
    x: -16,
    y: -6,
    size: 38,
    delay: 0.3,
    duration: 0.95,
  },
  {
    Icon: SiDocker,
    color: "#2496ED",
    x: 40,
    y: 4,
    size: 48,
    delay: 0.08,
    duration: 1.3,
  },
  {
    Icon: SiNestjs,
    color: "#E0234E",
    x: 42,
    y: 24,
    size: 42,
    delay: 0.2,
    duration: 1.15,
  },
  {
    Icon: SiMongodb,
    color: "#47A248",
    x: -40,
    y: 22,
    size: 46,
    delay: 0.15,
    duration: 1.28,
  },
  {
    Icon: SiPostgresql,
    color: "#5A86B0",
    x: -22,
    y: 32,
    size: 44,
    delay: 0.27,
    duration: 1.0,
  },
  {
    Icon: SiGo,
    color: "#00ADD8",
    x: 6,
    y: 36,
    size: 40,
    delay: 0.1,
    duration: 1.22,
  },
  {
    Icon: SiRust,
    color: "#D19070",
    x: 26,
    y: 34,
    size: 42,
    delay: 0.22,
    duration: 1.08,
  },
];

export const HERO_TAGLINE: HeroTaglinePart[] = [
  { text: "Think ", className: "" },
  {
    text: "Like An ",
    className: "",
  },
  { text: "ENGINEER", className: "text-brand-red font-semibold italic" },
];

export const HERO_TIMING = {
  CONVERGENCE_START: 1000,
  ENERGY_BURST_START: 2380,
  DEVELOPER_REVEAL: 2460,
  ENERGY_BURST_END: 3100,
  TYPOGRAPHY_REVEAL: 3100,
  TAGLINE_START: 3800,
  FINAL_STATE: 4700,
} as const;
